In [ ]:
import numpy as np
import pandas as pd

PROJECT1 = DS009

In [ ]:
student = {'name':['Adeola Oladele', 'Abolore Ishola', 'Oladayo Sanni', 'Mariam Kanyinsola', 'Peter Orioye', 'Ibrahim Adenuga', 'Olawunmi Abisola', 'Ayomikun Idowu', 'Hassan Musa', 'Ridwan Sobo'],
           'relationship':['Single', 'Divorced', 'Single', 'Married', 'Married','Single', 'Divorced', 'Single', 'Married', 'Married'],
           'age':[15, 56, 12, 26, 34, 25, 45, 19, 49, 36],
           'department':['PHE', 'FST', 'EEE', 'CHE', 'MEE', 'DST', 'DSS', 'GPY', 'GEO', 'MSE']}

In [ ]:
student ['name']

['Adeola Oladele',
 'Abolore Ishola',
 'Oladayo Sanni',
 'Mariam Kanyinsola',
 'Peter Orioye',
 'Ibrahim Adenuga',
 'Olawunmi Abisola',
 'Ayomikun Idowu',
 'Hassan Musa',
 'Ridwan Sobo']

In [ ]:
student['cgpa'] = [2.52, 3.69, 4.56, 4.53, 4.36, 4.77, 4.60, 2.54, 3.98, 4.86]


In [ ]:
student.pop('relationship')

['Single',
 'Divorced',
 'Single',
 'Married',
 'Married',
 'Single',
 'Divorced',
 'Single',
 'Married',
 'Married']

In [ ]:
df = pd.DataFrame(student)

In [ ]:
df

name  age department  cgpa
0     Adeola Oladele   15        PHE  2.52
1     Abolore Ishola   56        FST  3.69
2      Oladayo Sanni   12        EEE  4.56
3  Mariam Kanyinsola   26        CHE  4.53
4       Peter Orioye   34        MEE  4.36
5    Ibrahim Adenuga   25        DST  4.77
6   Olawunmi Abisola   45        DSS  4.60
7     Ayomikun Idowu   19        GPY  2.54
8        Hassan Musa   49        GEO  3.98
9        Ridwan Sobo   36        MSE  4.86

In [ ]:
df['admission_date'] = ['2014-08-24', '2012-05-30', '2014-08-24', '2011-05-25', '2010-08-04', '2022-05-30', '2011-08-24', '2012-05-30','2014-08-24', '2010-06-25' ]
df['gender'] = ['Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male']

In [ ]:
df

name  age department  cgpa admission_date  gender
0     Adeola Oladele   15        PHE  2.52     2014-08-24    Male
1     Abolore Ishola   56        FST  3.69     2012-05-30    Male
2      Oladayo Sanni   12        EEE  4.56     2014-08-24    Male
3  Mariam Kanyinsola   26        CHE  4.53     2011-05-25  Female
4       Peter Orioye   34        MEE  4.36     2010-08-04    Male
5    Ibrahim Adenuga   25        DST  4.77     2022-05-30    Male
6   Olawunmi Abisola   45        DSS  4.60     2011-08-24  Female
7     Ayomikun Idowu   19        GPY  2.54     2012-05-30  Female
8        Hassan Musa   49        GEO  3.98     2014-08-24    Male
9        Ridwan Sobo   36        MSE  4.86     2010-06-25    Male

In [ ]:
student2 = [['Adeola Oladele', 'Abolore Ishola', 'Oladayo Sanni', 'Mariam Kanyinsola', 'Peter Orioye', 'Ibrahim Adenuga', 'Olawunmi Abisola', 'Ayomikun Idowu', 'Hassan Musa', 'Ridwan Sobo'], ['Single', 'Divorced', 'Single', 'Married', 'Married','Single', 'Divorced', 'Single', 'Married', 'Married'], 
            [15, 56, 12, 26, 34, 25, 45, 19, 49, 36], ['PHE', 'FST', 'EEE', 'CHE', 'MEE', 'DST', 'DSS', 'GPY', 'GEO', 'MSE']]

In [ ]:
student2

[['Adeola Oladele',
  'Abolore Ishola',
  'Oladayo Sanni',
  'Mariam Kanyinsola',
  'Peter Orioye',
  'Ibrahim Adenuga',
  'Olawunmi Abisola',
  'Ayomikun Idowu',
  'Hassan Musa',
  'Ridwan Sobo'],
 ['Single',
  'Divorced',
  'Single',
  'Married',
  'Married',
  'Single',
  'Divorced',
  'Single',
  'Married',
  'Married'],
 [15, 56, 12, 26, 34, 25, 45, 19, 49, 36],
 ['PHE', 'FST', 'EEE', 'CHE', 'MEE', 'DST', 'DSS', 'GPY', 'GEO', 'MSE']]

In [ ]:
df2 = pd.DataFrame(student2)

In [ ]:
df['admission_date'] = ['2012-05-06', '2013-02-04','2020-04-06', '2003-02-04','2010-05-06', '2008-02-04','2012-05-06', '2016-06-04','2012-05-06', '2013-02-04']

In [ ]:
df

name  age department  cgpa admission_date  gender
0     Adeola Oladele   15        PHE  2.52     2012-05-06    Male
1     Abolore Ishola   56        FST  3.69     2013-02-04    Male
2      Oladayo Sanni   12        EEE  4.56     2020-04-06    Male
3  Mariam Kanyinsola   26        CHE  4.53     2003-02-04  Female
4       Peter Orioye   34        MEE  4.36     2010-05-06    Male
5    Ibrahim Adenuga   25        DST  4.77     2008-02-04    Male
6   Olawunmi Abisola   45        DSS  4.60     2012-05-06  Female
7     Ayomikun Idowu   19        GPY  2.54     2016-06-04  Female
8        Hassan Musa   49        GEO  3.98     2012-05-06    Male
9        Ridwan Sobo   36        MSE  4.86     2013-02-04    Male

In [ ]:
import datetime as dt

In [ ]:
df['admission_date'] = pd.to_datetime(df['admission_date'])
df['year'] = df['admission_date'].dt.year
df['month'] = df['admission_date'].dt.month
df['day'] = df['admission_date'].dt.day

In [ ]:
df

name  age department  cgpa admission_date  gender  year  \
0     Adeola Oladele   15        PHE  2.52     2012-05-06    Male  2012   
1     Abolore Ishola   56        FST  3.69     2013-02-04    Male  2013   
2      Oladayo Sanni   12        EEE  4.56     2020-04-06    Male  2020   
3  Mariam Kanyinsola   26        CHE  4.53     2003-02-04  Female  2003   
4       Peter Orioye   34        MEE  4.36     2010-05-06    Male  2010   
5    Ibrahim Adenuga   25        DST  4.77     2008-02-04    Male  2008   
6   Olawunmi Abisola   45        DSS  4.60     2012-05-06  Female  2012   
7     Ayomikun Idowu   19        GPY  2.54     2016-06-04  Female  2016   
8        Hassan Musa   49        GEO  3.98     2012-05-06    Male  2012   
9        Ridwan Sobo   36        MSE  4.86     2013-02-04    Male  2013   

   month  day  
0      5    6  
1      2    4  
2      4    6  
3      2    4  
4      5    6  
5      2    4  
6      5    6  
7      6    4  
8      5    6  
9      2    4

In [ ]:
df.dtypes

name                      object
age                        int64
department                object
cgpa                     float64
admission_date    datetime64[ns]
gender                    object
year                       int64
month                      int64
day                        int64
dtype: object

In [ ]:
df.isnull().sum()

name              0
age               0
department        0
cgpa              0
admission_date    0
gender            0
year              0
month             0
day               0
dtype: int64

In [ ]:
df.isnull().sum()/df.shape[0] *100

name              0.0
age               0.0
department        0.0
cgpa              0.0
admission_date    0.0
gender            0.0
year              0.0
month             0.0
day               0.0
dtype: float64

In [ ]:
df.name.unique()

array(['Adeola Oladele', 'Abolore Ishola', 'Oladayo Sanni',
       'Mariam Kanyinsola', 'Peter Orioye', 'Ibrahim Adenuga',
       'Olawunmi Abisola', 'Ayomikun Idowu', 'Hassan Musa', 'Ridwan Sobo'],
      dtype=object)

In [ ]:
df.age.unique()

array([15, 56, 12, 26, 34, 25, 45, 19, 49, 36])

In [ ]:
df.department.unique()

array(['PHE', 'FST', 'EEE', 'CHE', 'MEE', 'DST', 'DSS', 'GPY', 'GEO',
       'MSE'], dtype=object)

In [ ]:
df.cgpa.unique()


array([2.52, 3.69, 4.56, 4.53, 4.36, 4.77, 4.6 , 2.54, 3.98, 4.86])

In [ ]:
df.admission_date.unique()

array(['2012-05-06T00:00:00.000000000', '2013-02-04T00:00:00.000000000',
       '2020-04-06T00:00:00.000000000', '2003-02-04T00:00:00.000000000',
       '2010-05-06T00:00:00.000000000', '2008-02-04T00:00:00.000000000',
       '2016-06-04T00:00:00.000000000'], dtype='datetime64[ns]')

In [ ]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df.month.unique()

array([5, 2, 4, 6])

In [ ]:
df.day.unique()

array([6, 4])

In [ ]:
df.name.nunique()

10

In [ ]:
df.age.nunique()

10

In [ ]:
df.department.nunique()

10

In [ ]:
df.cgpa.nunique()

10

In [ ]:
df.admission_date.nunique()

7

In [ ]:
df.gender.nunique()

2

In [ ]:
df.month.nunique()

4

In [ ]:
df.day.nunique()

2

In [ ]:
df.name.value_counts()

Adeola Oladele       1
Abolore Ishola       1
Oladayo Sanni        1
Mariam Kanyinsola    1
Peter Orioye         1
Ibrahim Adenuga      1
Olawunmi Abisola     1
Ayomikun Idowu       1
Hassan Musa          1
Ridwan Sobo          1
Name: name, dtype: int64

In [ ]:
df.isnull().sum()/df.shape[0] *100


name              0.0
age               0.0
department        0.0
cgpa              0.0
admission_date    0.0
gender            0.0
year              0.0
month             0.0
day               0.0
dtype: float64

In [ ]:
df.age.value_counts()

15    1
56    1
12    1
26    1
34    1
25    1
45    1
19    1
49    1
36    1
Name: age, dtype: int64

In [ ]:
df.department.value_counts()

PHE    1
FST    1
EEE    1
CHE    1
MEE    1
DST    1
DSS    1
GPY    1
GEO    1
MSE    1
Name: department, dtype: int64

In [ ]:
df.cgpa.value_counts()

2.52    1
3.69    1
4.56    1
4.53    1
4.36    1
4.77    1
4.60    1
2.54    1
3.98    1
4.86    1
Name: cgpa, dtype: int64

In [ ]:
df.admission_date.value_counts()

2012-05-06    3
2013-02-04    2
2020-04-06    1
2003-02-04    1
2010-05-06    1
2008-02-04    1
2016-06-04    1
Name: admission_date, dtype: int64

In [ ]:
df.gender.value_counts()

Male      7
Female    3
Name: gender, dtype: int64

In [ ]:
df.year.value_counts()

2012    3
2013    2
2020    1
2003    1
2010    1
2008    1
2016    1
Name: year, dtype: int64

In [ ]:
df.month.value_counts()

5    4
2    4
4    1
6    1
Name: month, dtype: int64

In [ ]:
df.day.value_counts()

6    5
4    5
Name: day, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   name            10 non-null     object        
 1   age             10 non-null     int64         
 2   department      10 non-null     object        
 3   cgpa            10 non-null     float64       
 4   admission_date  10 non-null     datetime64[ns]
 5   gender          10 non-null     object        
 6   year            10 non-null     int64         
 7   month           10 non-null     int64         
 8   day             10 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 848.0+ bytes


In [ ]:
df.describe().T

count      mean        std      min        25%       50%      75%  \
age     10.0    31.700  14.892578    12.00    20.5000    30.000    42.75   
cgpa    10.0     4.041   0.870395     2.52     3.7625     4.445     4.59   
year    10.0  2011.900   4.508018  2003.00  2010.5000  2012.000  2013.00   
month   10.0     3.800   1.619328     2.00     2.0000     4.500     5.00   
day     10.0     5.000   1.054093     4.00     4.0000     5.000     6.00   

           max  
age      56.00  
cgpa      4.86  
year   2020.00  
month     6.00  
day       6.00

In [ ]:
df.shape[0]

10

In [ ]:
df.query('age > 20')

name  age department  cgpa admission_date  gender  year  \
1     Abolore Ishola   56        FST  3.69     2013-02-04    Male  2013   
3  Mariam Kanyinsola   26        CHE  4.53     2003-02-04  Female  2003   
4       Peter Orioye   34        MEE  4.36     2010-05-06    Male  2010   
5    Ibrahim Adenuga   25        DST  4.77     2008-02-04    Male  2008   
6   Olawunmi Abisola   45        DSS  4.60     2012-05-06  Female  2012   
8        Hassan Musa   49        GEO  3.98     2012-05-06    Male  2012   
9        Ridwan Sobo   36        MSE  4.86     2013-02-04    Male  2013   

   month  day  
1      2    4  
3      2    4  
4      5    6  
5      2    4  
6      5    6  
8      5    6  
9      2    4

In [ ]:
df.query('gender == Male')

UndefinedVariableError: ignored

In [ ]:
df.cgpa.sum()

In [ ]:
df.cgpa.mean()

In [ ]:
df.cgpa.max()

In [ ]:
df.cgpa.min()

In [ ]:
df.to_csv('student.csv', index= False)

In [ ]:
pd.read_csv('student.csv')